### PR TITLE
Port tests and SigningKey to Python 3 bytestrings

### PR DESCRIPTION
**Pull request by StarGate01**
This PR fixes the tests, which are a few years old at this point. (`python3 setup.py test`)
The newer versions of `ecdsa` use bytestrings to represent keys (on Python 3).

In general, this PR uses bytestrings for arrays of bytes instead of Python 2 - style strings.

### CODE REVIEW

**Comment by hathach** [comment]
@dhalbert would you mind reviewing this, since you are doing python 2 -> 3 migration for this utils iirc. No problems if you don't have time, I will try my best.

**Review by hathach — APPROVED** [review]
thank you very much for the PR, the detail explanation does indeed help a lot with reviewing. I did compile and test uploading, everything works well. However, I still have issue running `python3 setup.py test`

```
AttributeError: module 'collections' has no attribute 'Callable'
```

a quick google seem to indicate it seems to be module issue with python 3.10, several answer is downgrading to 3.9 and has nothing to do with us.

**Comment by StarGate01** [comment]
Thanks for merging! For me, it works fine using  `Python 3.10.4` Make sure to `mkdir -p test-reports` before testing.

Do you plan on releasing a new tag / release (`0.5.3.post18`) ?

**Comment by hathach** [comment]
Since this PR mostly fix the internal tests and have no impact on the actual functionality of the package. Therefore we don't really need to release it unless you have any specific reason for the new release.

**Comment by StarGate01** [comment]
I see your point, thanks for the explanation 👍
